apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiren-app
  labels:
    app: kiren-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kiren-app
  template:
    metadata:
      labels:
        app: kiren-app
    spec:
      containers:
      - name: kiren
        image: mertcanaltin/kiren:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kiren-service
spec:
  selector:
    app: kiren-app
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer